#!/bin/bash


CUDA_VISIBLE_DEVICES=2 python main_seed.py \
    DATA.NAME PSM \
    ORACLEAD.CAUSAL_ENCODER.MODE topk \
    ORACLEAD.CAUSAL_ENCODER.TOPK 1 \

CUDA_VISIBLE_DEVICES=2 python main_seed.py \
    DATA.NAME PSM \
    ORACLEAD.CAUSAL_ENCODER.MODE topk \
    ORACLEAD.CAUSAL_ENCODER.TOPK 2 \

CUDA_VISIBLE_DEVICES=2 python main_seed.py \
    DATA.NAME PSM \
    ORACLEAD.CAUSAL_ENCODER.MODE topk \
    ORACLEAD.CAUSAL_ENCODER.TOPK 5 \

CUDA_VISIBLE_DEVICES=2 python main_seed.py \
    DATA.NAME PSM \
    ORACLEAD.CAUSAL_ENCODER.MODE linear \
    ORACLEAD.CAUSAL_ENCODER.PROJ_DIM 8 \

CUDA_VISIBLE_DEVICES=2 python main_seed.py \
    DATA.NAME PSM \
    ORACLEAD.CAUSAL_ENCODER.MODE linear \
    ORACLEAD.CAUSAL_ENCODER.PROJ_DIM 32 \

CUDA_VISIBLE_DEVICES=2 python main_seed.py \
    DATA.NAME PSM \
    ORACLEAD.CAUSAL_ENCODER.MODE linear \
    ORACLEAD.CAUSAL_ENCODER.PROJ_DIM 64 \

CUDA_VISIBLE_DEVICES=2 python main_seed.py \
    DATA.NAME PSM \
    ORACLEAD.CAUSAL_ENCODER.MODE linear \
    ORACLEAD.CAUSAL_ENCODER.PROJ_DIM 128 \


echo "All experiments completed."